const { test } = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { createRequire } = require('node:module')
const { pathToFileURL } = require('node:url')
const { scaffold } = require('../dist/scaffold.js')
const { writeJson, readJson, run } = require('../dist/common.js')
const { preparePackage } = require('../dist/package.js')

test('dedicated repo develops through a Yarn portal, shares React, rebuilds, regenerates and packs releases', { skip: !process.env.OPEN_MERCATO_ROOT, timeout: 180000 }, async (context) => {
  const framework = fs.realpathSync(process.env.OPEN_MERCATO_ROOT)
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'mercato-repo-development-'))
  context.after(() => fs.rmSync(root, { recursive: true, force: true }))
  const source = path.join(root, 'source-app')
  const app = path.join(root, 'test-app')
  const repository = path.join(root, 'mercato-visits')
  const version = readJson(path.join(framework, 'packages/core/package.json')).version
  const reactVersion = readJson(path.join(framework, 'node_modules/react/package.json')).version
  const sourceManifest = { name: 'source-app', private: true, dependencies: { '@open-mercato/core': version, '@open-mercato/shared': version, '@open-mercato/ui': version, react: reactVersion } }
  writeJson(path.join(source, 'package.json'), sourceManifest)
  fs.mkdirSync(path.join(source, 'src/modules'), { recursive: true })
  fs.writeFileSync(path.join(source, 'src/modules.ts'), 'export const enabledModules = []\n')
  fs.symlinkSync(path.join(framework, 'node_modules'), path.join(source, 'node_modules'))
  scaffold({ directory: source, manifest: sourceManifest }, 'visits')
  const exported = path.join(root, 'export')
  preparePackage({ directory: source, manifest: sourceManifest }, 'visits', { packageName: '@fixture/visits', version: '0.1.0', repository: '', access: 'public' }, exported)
  run('git', ['init', '-q', '--initial-branch=main'], exported, { capture: true })
  run('git', ['-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.com', 'add', '.'], exported, { capture: true })
  run('git', ['-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.com', 'commit', '-qm', 'Initial module snapshot'], exported, { capture: true })
  run('git', ['clone', exported, repository], root, { capture: true })
  const dependencies = { react: reactVersion, 'react-dom': reactVersion, typescript: require('typescript/package.json').version }
  for (const name of ['core', 'shared', 'ui']) {
    const stub = path.join(root, `peer-${name}`)
    writeJson(path.join(stub, 'package.json'), { name: `@open-mercato/${name}`, version })
    dependencies[`@open-mercato/${name}`] = `file:../peer-${name}`
  }
  writeJson(path.join(app, 'package.json'), { name: 'test-app', private: true, packageManager: 'yarn@4.17.1', dependencies })
  fs.writeFileSync(path.join(app, '.yarnrc.yml'), 'nodeLinker: node-modules\nenableGlobalCache: true\n')
  fs.mkdirSync(path.join(app, 'src/modules'), { recursive: true })
  fs.cpSync(path.join(source, 'src/modules/visits'), path.join(app, 'src/modules/visits'), { recursive: true })
  fs.copyFileSync(path.join(source, 'src/modules.ts'), path.join(app, 'src/modules.ts'))
  fs.writeFileSync(path.join(app, 'next.config.ts'), 'export default {}\n')
  const linked = run('yarn', ['add', '@fixture/visits@portal:../mercato-visits'], app, { capture: true, allowFailure: true })
  assert.equal(linked.status, 0, `${linked.stdout}\n${linked.stderr}`)
  assert.equal(fs.realpathSync(path.join(app, 'node_modules/@fixture/visits')), repository)
  fs.symlinkSync(path.join(app, 'node_modules'), path.join(repository, 'node_modules'))
  assert.equal(createRequire(path.join(repository, 'package.json')).resolve('react'), createRequire(path.join(app, 'package.json')).resolve('react'))
  for (const name of ['core', 'shared', 'ui']) {
    const installed = path.join(app, 'node_modules/@open-mercato', name)
    for (const entry of ['src', 'dist']) fs.symlinkSync(path.join(framework, 'packages', name, entry), path.join(installed, entry))
  }
  fs.mkdirSync(path.join(app, '.module-backups'))
  fs.renameSync(path.join(app, 'src/modules/visits'), path.join(app, '.module-backups/visits'))
  const moduleRoot = path.join(repository, 'src/modules/visits')
  function writeFeature(label) {
    fs.writeFileSync(path.join(moduleRoot, 'backend/visits/page.tsx'), `'use client'\nimport { useState } from 'react'\nexport default function VisitsPage() { const [label] = useState('${label}'); return <h1>{label}</h1> }\n`)
    fs.mkdirSync(path.join(moduleRoot, 'api'), { recursive: true })
    fs.writeFileSync(path.join(moduleRoot, 'api/status.ts'), `export const metadata = { GET: { requireAuth: true } }\nexport async function GET() { return Response.json({ label: '${label}' }) }\n`)
    writeJson(path.join(moduleRoot, 'i18n/en.json'), { 'visits.title': label })
  }
  writeFeature('Repository version one')
  run('npm', ['run', 'build'], repository, { capture: true })
  const cli = path.join(framework, 'packages/cli/dist/bin.js')
  fs.writeFileSync(path.join(app, 'src/modules.ts'), 'export const enabledModules = []\n')
  const enabled = run(process.execPath, [cli, 'module', 'enable', '@fixture/visits', '--allow-third-party'], app, { capture: true, allowFailure: true })
  assert.equal(enabled.status, 0, `${enabled.stdout}\n${enabled.stderr}`)
  assert.match(fs.readFileSync(path.join(app, 'src/modules.ts'), 'utf8'), /from: ['"]@fixture\/visits['"]/)
  const appRequire = createRequire(path.join(app, 'package.json'))
  const react = appRequire('react')
  const { renderToStaticMarkup } = appRequire('react-dom/server')
  async function assertRuntime(label, revision) {
    const pagePath = appRequire.resolve('@fixture/visits/modules/visits/backend/visits/page')
    const routePath = appRequire.resolve('@fixture/visits/modules/visits/api/status')
    const page = await import(`${pathToFileURL(pagePath).href}?revision=${revision}`)
    const route = await import(`${pathToFileURL(routePath).href}?revision=${revision}`)
    assert.equal(renderToStaticMarkup(react.createElement(page.default)), `<h1>${label}</h1>`)
    assert.deepEqual(await (await route.GET()).json(), { label })
    assert.equal(readJson(appRequire.resolve('@fixture/visits/modules/visits/i18n/en.json'))['visits.title'], label)
  }
  await assertRuntime('Repository version one', 1)
  writeFeature('Repository version two')
  fs.mkdirSync(path.join(moduleRoot, 'backend/visits/reports'), { recursive: true })
  fs.writeFileSync(path.join(moduleRoot, 'backend/visits/reports/page.tsx'), 'export default function Reports() { return <p>New report</p> }\n')
  run('npm', ['run', 'build'], repository, { capture: true })
  const regenerated = run(process.execPath, [cli, 'generate'], app, { capture: true, allowFailure: true })
  assert.equal(regenerated.status, 0, `${regenerated.stdout}\n${regenerated.stderr}`)
  await assertRuntime('Repository version two', 2)
  const outputDirectory = path.join(app, '.mercato/generated')
  const registries = fs.readdirSync(outputDirectory).filter((name) => name.endsWith('.ts')).map((name) => fs.readFileSync(path.join(outputDirectory, name), 'utf8')).join('\n')
  assert.match(registries, /@fixture\/visits\/modules\/visits\/backend\/visits\/reports\/page/)
  assert.match(registries, /@fixture\/visits\/modules\/visits\/api\/status/)
  assert.doesNotMatch(registries, /\.\.\/\.\.\/src\/modules\/visits\//)
  assert.match(fs.readFileSync(path.join(outputDirectory, 'module-package-sources.css'), 'utf8'), /mercato-visits\/src/)
  run('npm', ['version', 'patch', '--no-git-tag-version'], repository, { capture: true })
  const packed = JSON.parse(run('npm', ['pack', '--json'], repository, { capture: true }).stdout)[0]
  assert.equal(packed.version, '0.1.1')
  assert.ok(packed.files.some((file) => file.path === 'dist/modules/visits/backend/visits/reports/page.js'))
  assert.ok(packed.files.every((file) => !file.path.includes('node_modules') && !file.path.includes('.module-backups')))
  const archived = run('tar', ['-xOzf', path.join(repository, packed.filename), 'package/dist/modules/visits/api/status.js'], repository, { capture: true }).stdout
  assert.match(archived, /Repository version two/)
  assert.ok(fs.existsSync(path.join(app, '.module-backups/visits/index.ts')))
  assert.ok(!fs.existsSync(path.join(app, 'src/modules/visits')))
})
